### PR TITLE
Unbreak console builds, remove warnings, personal tweaks

### PR DESCRIPTION
**Pull request by poldy**
Hi,
These are the local changes I run with. If you like, we could discuss getting them back upstream.

### CODE REVIEW

**Comment by peterhellberg** [comment]
I’m getting the following errors when running **make**

``` bash
Undefined symbols for architecture x86_64:
  "_echo_off", referenced from:
      _emulate_readline in keyboard-111d1b.o
      _shift_down in keyboard-111d1b.o
      _display in keyboard-111d1b.o
      _shift_up in keyboard-111d1b.o
      _fn_tab in iostate-66ad3b.o
      _fn_spc in iostate-66ad3b.o
      _emulate_oscli in emulate-97c431.o
      ...
  "_echo_on", referenced from:
      _emulate_readline in keyboard-111d1b.o
      _shift_down in keyboard-111d1b.o
      _display in keyboard-111d1b.o
      _shift_up in keyboard-111d1b.o
      _fn_tab in iostate-66ad3b.o
      _fn_spc in iostate-66ad3b.o
      _emulate_oscli in emulate-97c431.o
      ...
  "_emulate_circle", referenced from:
      _exec_circle in iostate-66ad3b.o
  "_emulate_colourfn", referenced from:
      _fn_colour in functions-91b8e8.o
  "_emulate_colourtint", referenced from:
      _exec_colnum in iostate-66ad3b.o
  "_emulate_defcolour", referenced from:
      _exec_colnum in iostate-66ad3b.o
  "_emulate_draw", referenced from:
      _exec_draw in iostate-66ad3b.o
  "_emulate_drawby", referenced from:
      _exec_drawby in iostate-66ad3b.o
  "_emulate_drawrect", referenced from:
      _exec_rectangle in iostate-66ad3b.o
  "_emulate_ellipse", referenced from:
      _exec_ellipse in iostate-66ad3b.o
  "_emulate_fill", referenced from:
      _exec_fill in iostate-66ad3b.o
  "_emulate_fillby", referenced from:
      _exec_fillby in iostate-66ad3b.o
  "_emulate_gcol", referenced from:
      _exec_gcolnum in iostate-66ad3b.o
  "_emulate_gcolnum", referenced from:
      _exec_gcolofon in iostate-66ad3b.o
  "_emulate_gcolrgb", referenced from:
      _exec_gcolofon in iostate-66ad3b.o
      _exec_gcolnum in iostate-66ad3b.o
  "_emulate_line", referenced from:
      _exec_line in iostate-66ad3b.o
  "_emulate_mapcolour", referenced from:
      _exec_colnum in iostate-66ad3b.o
  "_emulate_mode", referenced from:
      _exec_modenum in iostate-66ad3b.o
      _exec_modestr in iostate-66ad3b.o
  "_emulate_modefn", referenced from:
      _fn_mode in functions-91b8e8.o
  "_emulate_modestr", referenced from:
      _exec_modestr in iostate-66ad3b.o
  "_emulate_move", referenced from:
      _exec_move in iostate-66ad3b.o
  "_emulate_moveby", referenced from:
      _exec_moveby in iostate-66ad3b.o
  "_emulate_moverect", referenced from:
      _exec_rectangle in iostate-66ad3b.o
  "_emulate_newline", referenced from:
      _read_input in iostate-66ad3b.o
      _print_screen in iostate-66ad3b.o
      _fn_tab in iostate-66ad3b.o
  "_emulate_newmode", referenced from:
      _exec_modenum in iostate-66ad3b.o
  "_emulate_off", referenced from:
      _exec_off in iostate-66ad3b.o
  "_emulate_on", referenced from:
      _exec_on in mainstate-972188.o
  "_emulate_origin", referenced from:
      _exec_origin in iostate-66ad3b.o
  "_emulate_plot", referenced from:
      _exec_plot in iostate-66ad3b.o
  "_emulate_point", referenced from:
      _exec_point in iostate-66ad3b.o
  "_emulate_pointby", referenced from:
      _exec_pointby in iostate-66ad3b.o
  "_emulate_pointfn", referenced from:
      _fn_pointfn in functions-91b8e8.o
  "_emulate_pointto", referenced from:
      _exec_pointto in iostate-66ad3b.o
  "_emulate_pos", referenced from:
      _fn_pos in functions-91b8e8.o
  "_emulate_printf", referenced from:
      _list_variables in variables-c3fc18.o
      _list_varlist in variables-c3fc18.o
      _detail_library in variables-c3fc18.o
      _list_libraries in variables-c3fc18.o
      _show_byte in miscprocs-708788.o
      _show_word in miscprocs-708788.o
      _announce in errors-6ab0a0.o
      ...
  "_emulate_setcolnum", referenced from:
      _exec_colofon in iostate-66ad3b.o
  "_emulate_setcolour", referenced from:
      _exec_colofon in iostate-66ad3b.o
      _exec_colnum in iostate-66ad3b.o
  "_emulate_tab", referenced from:
      _fn_tab in iostate-66ad3b.o
  "_emulate_tint", referenced from:
      _exec_tint in iostate-66ad3b.o
  "_emulate_tintfn", referenced from:
      _fn_tint in functions-91b8e8.o
  "_emulate_vdu", referenced from:
      _list_variables in variables-c3fc18.o
      _list_varlist in variables-c3fc18.o
      _show_byte in miscprocs-708788.o
      _show_word in miscprocs-708788.o
      _emulate_readline in keyboard-111d1b.o
      _shift_down in keyboard-111d1b.o
      _display in keyboard-111d1b.o
      ...
  "_emulate_vdufn", referenced from:
      _fn_vdu in functions-91b8e8.o
  "_emulate_vdustr", referenced from:
      _trace_line in statement-b96a30.o
      _trace_proc in statement-b96a30.o
      _trace_branch in statement-b96a30.o
      _exec_report in mainstate-972188.o
      _emulate_readline in keyboard-111d1b.o
      _recall_histline in keyboard-111d1b.o
      _read_input in iostate-66ad3b.o
      ...
  "_emulate_vpos", referenced from:
      _fn_vpos in functions-91b8e8.o
  "_emulate_wait", referenced from:
      _exec_wait in mainstate-972188.o
     (maybe you meant: _emulate_waitdelay)
  "_end_screen", referenced from:
      _exit_interpreter in brandy-694c57.o
  "_find_cursor", referenced from:
      _emulate_oscli in emulate-97c431.o
  "_init_screen", referenced from:
      _init2 in brandy-694c57.o
  "_set_cursor", referenced from:
      _emulate_readline in keyboard-111d1b.o
      _init_keyboard in keyboard-111d1b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by peterhellberg** [comment]
I’m running the following env:

``` bash
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.4
BuildVersion:   14E46

$ sdl-config --version
1.2.15
```

**Comment by poldy** [comment]
Ah, "make", my old nemesis.

Sorry about that, I mostly use "make nodebug GUI=console". I had broken the default targets. Should be fixed now, the Makefile may be due for a revamp but I won't do that right now.

I've tested this on exactly the same OS & toolchain as you. Also tested on NetBSD 6.1.2. I also tried msys2 on Windows, but some more debugging is required there.

**Comment by peterhellberg** [comment]
Looks good now :+1:

**Pull request merged**
